[project]
name = "lms"
authors = [{ name = "Setuware Technologies" }]
description = "Employee management app (attendance, leave, tasks) for Setuware Technologies"
requires-python = ">=3.10"
keywords = ["frappe", "erpnext", "lms", "employee"]
dependencies = ["frappe"]
version = "0.0.1"
readme = "README.md"
license = { text = "MIT" }

[tool.bench]
type = "app"

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.module]
name = "lms"
